{% set name = "duckdb" %}
{% set version = "0.3.4" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cwida/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 74863d60977fcb7768c300a0f10a90fbbd3087e310edd42b8e1b1dc5513835dd
  patches:
    # - 487.patch
    - 0001-make-protobuf-linkable.patch

build:
  number: 1
  skip: true  # [win]
  script: 
  # install buf
  - set -e
  - set -x
  - env | sort
  - export GOBIN="${BUILD_PREFIX}/bin"
  - export GO111MODULE=on
  - go install github.com/bufbuild/buf/cmd/buf@v1.5.0
  - which buf
  # regenerate substrait to match the linked protobuf version
  - python scripts/update_substrait.py
  - rm -rf third_party/google/protobuf
  - export USE_SYSTEM_PROTOBUF=true
  - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  - cd tools/pythonpkg && $PREFIX/bin/python setup.py install
  ignore_run_exports:
    - arrow-cpp

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - arrow-cpp                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - go-nocgo
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.4
    - python
    - pip
    - setuptools_scm
    - numpy
    - pandas
    - arrow-cpp
    - pyarrow
    - libprotobuf
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - arrow-cpp
    - pyarrow
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - duckdb
  requires:
    - pip
    - pytest
    - mypy
  source_files:
    - tools/pythonpkg/tests
  commands:
    - pip check
    # ppc64le is emulated and fails to run the test suite here
    - pytest tools/pythonpkg/tests  # [not ppc64le]

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://www.duckdb.org/docs/current/index.html
  dev_url: https://github.com/cwida/duckdb

extra:
  recipe-maintainers:
    - xhochy
    - mariusvniekerk
