{% set name = "duckdb" %}
{% set version = "0.3.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cwida/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ae2367d0a393be59e137ffa975f48f60b113b2a72aacc24fbc59afa0cbc3a511
  patches:
    # - 487.patch

build:
  number: 0
  skip: true  # [win]
  script: cd tools/pythonpkg && SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} $PREFIX/bin/python setup.py install
  ignore_run_exports:
    - arrow-cpp

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - arrow-cpp                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.4
    - python
    - pip
    - setuptools_scm
    - numpy
    - pandas
    - arrow-cpp
    - pyarrow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - arrow-cpp
    - pyarrow
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - duckdb
  requires:
    - pip
    - pytest
  source_files:
    - tools/pythonpkg/tests
  commands:
    - pip check
    # ppc64le is emulated and fails to run the test suite here
    - pytest tools/pythonpkg/tests  # [not ppc64le]

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://www.duckdb.org/docs/current/index.html
  dev_url: https://github.com/cwida/duckdb

extra:
  recipe-maintainers:
    - xhochy
    - mariusvniekerk
