{% set name = "duckdb" %}
{% set version = "0.5.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/duckdb/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3dab7ba0d0f8d024d3c73fd3d4fb8834203c31d7b0ddb1e8539ee266e11b0e9b
  patches:

build:
  number: 1
  skip: true  # [win]
  script:
  # install buf
    - set -e
    - set -x
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - cd tools/pythonpkg && $PREFIX/bin/python setup.py install
  ignore_run_exports:
    - arrow-cpp

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - arrow-cpp                              # [build_platform != target_platform]
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.4
    - python
    - pip
    - setuptools_scm
    - numpy
    - pandas
    - arrow-cpp
    - pyarrow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - arrow-cpp
    - pyarrow
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - duckdb
  requires:
    - pip
    - pytest
    - mypy
    - google-cloud-storage
  source_files:
    - tools/pythonpkg/tests
  files:
    - test_extension_install.py
  commands:
    - pip check
    # ppc64le/aarch64 is emulated and fails to run the test suite here
    - pytest tools/pythonpkg/tests  # [not (ppc64le or aarch64)]
    # DuckDB not currently building extensions for linux-aarch64
    - python test_extension_install.py  # [not (linux and aarch64)]

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://www.duckdb.org/docs/current/index.html
  dev_url: https://github.com/cwida/duckdb

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
    - mariusvniekerk
    - gforsyth
