{% set name = "duckdb" %}
# Please also set OVERRIDE_GIT_DESCRIBE in build-duckdb.{sh,bat}
{% set version = "1.4.0" %}

package:
  name: python-{{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd5edee8bd5a73b5822f2b390668597b5fcdc2d3292c244d8d933bb87ad6ac4c

build:
  number: 0

outputs:
  - name: python-{{ name|lower }}
    script: build-duckdb.sh  # [unix]
    script: build-duckdb.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11 >=2.6                         # [build_platform != target_platform]
        - cmake >=3.29
        - ninja
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - pybind11 >=2.6
        - scikit-build-core >=0.11.4
        - python
        - pip
        - setuptools
        - setuptools_scm >=8
      run:
        - python

    test:
      imports:
        - duckdb
      requires:
        - pip
      commands:
        - pip check
  - name: {{ name|lower }}
    build:
      noarch: generic
      skip: true  # [not linux64]
    requirements:
      run:
        - {{ pin_subpackage('python-duckdb', max_pin="x.x.x") }}
    test:
      imports:
        - duckdb


about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb

extra:
  recipe-maintainers:
    - jonashaag
    - sugatoray
    - dhirschfeld
    - xhochy
    - mariusvniekerk
    - gforsyth
