{% set name = "duckdb" %}
{% set version = "0.1.6" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cwida/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fdb7b38082dcf55aafd51bea81036bc9efed95a99ac9fa5d76f1f876be909cd1
  patches:
    - 487.patch

build:
  number: 0
  skip: true  # [win]
  script: cd tools/pythonpkg && SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} $PREFIX/bin/python setup.py install

requirements:
  build:
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.4
    - python
    - pip
    - setuptools_scm
    - numpy 1.16
    - pandas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas

test:
  imports:
    - duckdb
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://www.duckdb.org/docs/current/index.html
  dev_url: https://github.com/cwida/duckdb

extra:
  recipe-maintainers:
    - xhochy
