{% set name = "duckdb" %}
{% set version = "0.10.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/duckdb/duckdb.git
  git_rev: d93ce2952729d0e0af7334d2e55d4800f8b00175
  # url: https://github.com/duckdb/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: afff7bd925a98dc2af4039b8ab2159b0705cbf5e0ee05d97f7bb8dce5f880dc2
  patches:
    - 0001-fix-arrowfs-skip-arrow-fs-test-on-windows.patch

build:
  skip: true  # [(not (win and py==311)) and (not (osx and arm64 and py==311))]
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.6                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pybind11 >=2.6
    - python
    - pip
    - setuptools_scm <7
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - duckdb
  requires:
    - pip
    - pytest
    - mypy
    - fsspec
    - google-cloud-storage
    - pandas
    # Remove again
    - pytest<8
    - pandas=2.0
  commands:
    - pip check
    # ppc64le/aarch64 is emulated and fails to run the test suite here
    # Skip slow tests to avoid memory issues in CI, skip stub tests that is fragile under new version of mypy
    # - pytest tools/pythonpkg/tests --ignore=tools/pythonpkg/tests/slow/ --ignore=tools/pythonpkg/tests/stubs/  # [not (ppc64le or aarch64)]

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb

extra:
  recipe-maintainers:
    - jonashaag
    - sugatoray
    - dhirschfeld
    - xhochy
    - mariusvniekerk
    - gforsyth
